import math

# Autogenerated with DRAKON Editor 1.31

def _main_0():
    #item 4
    imports()
    #item 5
    syntax_roles()


def imports():
    #item 13
    print("The Import statement above makes some other math code available within the project")
    print(math.pi)


def syntax_roles():
    #item 9
    N = "David"
    n = 30
    
    print('N is: '.format(N))
    print('n is: '.format(n))
    print("Python is case sensetive")

_main_0()
