# Autogenerated with DRAKON Editor 1.31

def _number_main():
    #item 6
    integers()
    #item 7
    floats()
    #item 8
    complexs()
    #item 9
    operators()
    #item 10
    casting()


def casting():
    #item 34
    print('casting is the process where you attempt to fit one data type into another')
    print("this process doesn't always work and can return an error")
    #item 35
    print(float.__doc__)
    
    a = '3.14'
    #print(a ** a)  # uncomment this
    print(float(a) ** float(a))


def complexs():
    #item 25
    print('python can even work with so called complex numbers')
    #item 24
    num = 10 + 20j
    num2 =  complex(10, 20)
    num_type = type(num)
    
    print('num: {} has the type {}'.format(num, num_type))
    
    print('num2: {} has the type {}'.format(num2, type(num2)))


def floats():
    #item 20
    print('There are different types of numbers')
    #item 19
    num = 10.10
    num_type = type(num)
    
    print('the number: {} has the type {}'.format(num, num_type))


def integers():
    #item 15
    print('python makes it easy to work with numbers')
    #item 14
    num = 10
    num_type = type(num)
    
    print('the number: {} has the type {}'.format(num, num_type))


def operators():
    #item 29
    print('python comes with build in operators, they are:')
    print("""+ - * / ** // % """)


