# Autogenerated with DRAKON Editor 1.31

def _main_strings():
    #item 6
    length()
    #item 7
    slicing()
    #item 8
    operator()
    #item 9
    string_casting()


def length():
    #item 15
    s = 'study and practice'
    print('{}: {}'.format(len(s), s))


def operator():
    #item 27
    s = 'study and practice'
    print( s * 2)


def slicing():
    #item 21
    s = 'study and practice'
    print('{}: {}'.format(s[:5], s[-8:]))


def string_casting():
    #item 33
    a = 3.1459
    b = [1, 2, 3, (4, 5), 6]
    print(str(a))
    print(str(b))


