# Autogenerated with DRAKON Editor 1.31

def exercise1():
    #item 10
    print("Hello, Student")
    print("Modify me")


def exercise2():
    #item 14
    #print("Hello, Student")
    print("Exercise 2 is running")
    print("Make sure this line is NOT running")


def exercise3():
    #item 19
    print("Hello, Student")
    print("Exercise 3 is trying to run")


def exercise4():
    #item 23
    # 2 + 2 should print out 4
    print("{}".format(2+2))
    #item 24
    # 2 - 3 should print out 
    print("{}".format(2-3))
    #item 25
    # 4*5 should print out 
    print("{}".format(4*5))


def exercise5():
    #item 32
    var1 = 2+2
    var2 = 2-3
    any_name = 4*5
    #item 29
    # 2 + 2 should print out 4
    print("{}".format(var1))
    #item 30
    # 2 - 3 should print out 
    print("{}".format(var2))
    #item 31
    # 4*5 should print out 
    print("{}".format(anyname))


def main():
    #item 5
    #exercise1()
    #exercise2()
    #exercise3()
    #exercise4()
    #exercise5()
    #item 15
    exercise6()

main()
