# Autogenerated with DRAKON Editor 1.31

def exercise1():
    #item 10
    print("Hello, Student")
    print("Modify me")


def exercise2():
    #item 14
    #print("Hello, Student")
    print("Exercise 2 is running")
    print("Make sure this line is NOT running")


def main():
    #item 5
    #exercise1()
    #item 15
    exercise2()

main()
