# Autogenerated with DRAKON Editor 1.31

def exercise1():
    #item 10
    print("Hello, Student")
    print("Modify me")


def exercise2():
    #item 14
    #print("Hello, Student")
    print("Exercise 2 is running")
    print("Make sure this line is NOT running")


def exercise3():
    #item 19
    print("Hello, Student")
    print("Exercise 3 is trying to run)


def main():
    #item 5
    #exercise1()
    #exercise2()
    #item 15
    exercise3()

main()
